---
- name: Gather Basic Information from HiveMQ
  hosts: all
  gather_facts: no
  become: yes
  become_user: root

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Display HiveMQ Service Configuration
      command: cat /etc/systemd/system/hivemq.service
      register: hivemq_service
      ignore_errors: yes

    - name: Display Basic HiveMQ Information
      debug:
        msg: |
          --- HiveMQ Service Configuration ---
          {{ hivemq_service.stdout | default("Not available") }}

